modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "cobblests"
version = "${version}"
displayName = "CobbleSTS"
authors = "Zonary123"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.cobblests]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobblests]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobblests]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.cobblests]]
modId = "cobblemon"
mandatory = true
versionRange = "[1.5.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.cobblests]]
modId = "gooeylibs2"
mandatory = true
versionRange = "[3.0.0,)"
ordering = "AFTER"
side = "BOTH"
